version: '3.7'

services:
  postgis:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres-data:
